openapi: 3.0.0
info:
  title: "Evolutionary Manufacturing Scheduler API"
  version: 1.0.0
paths:
  /problems:
    post: 
      summary: creates a problem phase 
      operationId: create_problem_phase
      requestBody:
        required: true
        content: application/json
          schema:
            $ref: '#/components/schemas/problem'
        
      responses:
        '200':
          description: the new created problem id
          
  /propblems/{problem_id}
  

components:
  schemas:
    problem:
      