# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.auto_generated_models.base_model_ import Model
from src.api.swagger_helpers import util


class ProblemBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, site_data_id: int=None):
        """ProblemBody - a model defined in Swagger

        :param site_data_id: The site_data_id of this ProblemBody.
        :type site_data_id: int
        """
        self.swagger_types = {
            'site_data_id': int
        }

        self.attribute_map = {
            'site_data_id': 'site_data_id'
        }
        self._site_data_id = site_data_id

    @classmethod
    def from_dict(cls, dikt) -> 'ProblemBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The problem_body of this ProblemBody.
        :rtype: ProblemBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def site_data_id(self) -> int:
        """Gets the site_data_id of this ProblemBody.


        :return: The site_data_id of this ProblemBody.
        :rtype: int
        """
        return self._site_data_id

    @site_data_id.setter
    def site_data_id(self, site_data_id: int):
        """Sets the site_data_id of this ProblemBody.


        :param site_data_id: The site_data_id of this ProblemBody.
        :type site_data_id: int
        """

        self._site_data_id = site_data_id
