# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.auto_generated_models.base_model_ import Model
from src.api.swagger_helpers import util


class ProblemIdGenerationsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None):
        """ProblemIdGenerationsBody - a model defined in Swagger

        :param id: The id of this ProblemIdGenerationsBody.
        :type id: int
        """
        self.swagger_types = {
            'id': int
        }

        self.attribute_map = {
            'id': 'id'
        }
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'ProblemIdGenerationsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The problem_id_generations_body of this ProblemIdGenerationsBody.
        :rtype: ProblemIdGenerationsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this ProblemIdGenerationsBody.


        :return: The id of this ProblemIdGenerationsBody.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this ProblemIdGenerationsBody.


        :param id: The id of this ProblemIdGenerationsBody.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")

        self._id = id
