# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from src.api.auto_generated_models.base_model_ import Model
from src.api.swagger_helpers import util


class SitedataBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, file: bytearray=None):
        """SitedataBody - a model defined in Swagger

        :param file: The file of this SitedataBody.
        :type file: bytearray
        """
        self.swagger_types = {
            'file': bytearray
        }

        self.attribute_map = {
            'file': 'file'
        }
        self._file = file

    @classmethod
    def from_dict(cls, dikt) -> 'SitedataBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The sitedata_body of this SitedataBody.
        :rtype: SitedataBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def file(self) -> bytearray:
        """Gets the file of this SitedataBody.


        :return: The file of this SitedataBody.
        :rtype: bytearray
        """
        return self._file

    @file.setter
    def file(self, file: bytearray):
        """Sets the file of this SitedataBody.


        :param file: The file of this SitedataBody.
        :type file: bytearray
        """

        self._file = file
