openapi: 3.0.2
info:
  title: "Evolutionary Manufacturing Scheduler API"
  version: 1.0.0
servers:
  - url: https://localhost:9999/api
paths:
  /schedule:
    post:
      summary: triggers a schedueling task
      operationId: src.api.api.trigger_sched
      responses:
        '200':
          description: bla bla
  /problem_data:
    post:
      summary: uploading a json file with problem data
      operationId: src.api.api.create_problem_data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: byte
      responses:
        '200':
          description: site data object created