openapi: 3.0.2
info:
  title: "Evolutionary Manufacturing Scheduler API"
  version: 1.0.0
servers:
  - url: https://localhost:9999/api
paths:
  /schedule:
    post:
      summary: triggers a schedueling task
      operationId: src.api.api.trigger_sched
      responses:
        '200':
          description: bla bla
  /site-data:
    post:
      summary: uploading a json file with site data
      operationId: src.api.api.create_problem_data
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: byte
      responses:
        '200':
          description: site data object created
  /problem:
    post:
      summary: create a new problem from a given site data (id)
      operationId: src.api.api.add_problem
      requestBody:
        description: related site data id
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  format: int32
        required: true
      responses:
        '200':
          description: successfully created new problem
      x-codegen-request-body-name: body
#  /problem/findById:
#    get:
#      summary: get problem by id
#      operationId: src.api.api.get_problem_by_id
#      parameters:
#        - name: id
#          in: query
#          schema:
#            type: integer
#          required: true
#      responses:
#        '200':
#          description: successfully fetched problem
#          content:
#            application/xml:
#              schema: